In [18]:
import torch
import numpy as np

In [19]:
scalar = torch.tensor(7)
scalar.item()

7

In [20]:
vector = torch.tensor([5,7])
vector

tensor([5, 7])

In [21]:
vector.ndim

1

In [22]:
vector.shape

torch.Size([2])

In [24]:
MATRIX = torch.tensor(np.array([[10,10,10],[10,10,10]]))
MATRIX

tensor([[10, 10, 10],
        [10, 10, 10]])

In [25]:
MATRIX.ndim

2

In [26]:
MATRIX.shape

torch.Size([2, 3])

In [28]:
TENSOR = torch.tensor(torch.zeros([3,3], dtype=torch.int32))
TENSOR

/var/folders/df/hddlkw715x3819_qsx0p2kc80000gn/T/ipykernel_1226/606229386.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  TENSOR = torch.tensor(torch.zeros([3,3], dtype=torch.int32))


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [29]:
TENSOR.ndim

2

In [30]:
TENSOR.shape

torch.Size([3, 3])

In [34]:
random_tensor = torch.rand(size=(3,3))
random_tensor, random_tensor.dtype

(tensor([[0.8484, 0.5941, 0.5395],
         [0.3968, 0.0351, 0.8969],
         [0.8871, 0.7004, 0.6483]]),
 torch.float32)

In [41]:
tensor = torch.tensor([1,2,3])
tensor += 10
tensor

tensor([11, 12, 13])

In [42]:
tensor *= 5
tensor

tensor([55, 60, 65])

In [43]:
tensor -= 15
tensor

tensor([40, 45, 50])

In [45]:
example_tensor = torch.rand(size=(3,3))
example_tensor

tensor([[0.2738, 0.4748, 0.5803],
        [0.0089, 0.9660, 0.4435],
        [0.1537, 0.8999, 0.5447]])

In [46]:
torch.multiply(example_tensor, 10)

tensor([[2.7383, 4.7476, 5.8029],
        [0.0893, 9.6597, 4.4351],
        [1.5368, 8.9993, 5.4474]])